[build]
  command = "Rscript -e \"babelquarto::render()\""
  publish = "_site"

[build.environment]
  BABELQUARTO_CI_URL = "https://anavalladares.netlify.app"
  R_VERSION = "4.3.2"
  QUARTO_VERSION = "1.4.555"
