name: Render Quarto website

on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.x'
          
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-gnutls-dev
      
      # Setup Quarto
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.4.555'
          
      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2 
        with: 
          packages: |
            github::ropensci-review-tools/babelquarto@a485fea

      # Render website (all languages)
      - name: Render website with babelquarto
        run: Rscript -e 'babelquarto::render_website()'

      # Commit generated _site
      - name: Achive site render
        uses: actions/upload-artifact@v4
        with:
          name: site_render
          path: _site/
      - name: Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
