name: Render Quarto website

on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'
          
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      # Setup Quarto
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.4.555'

      # Render website (all languages)
      - name: Render website with babelquarto
        run: Rscript -e 'babelquarto::render_website()'

      # Commit generated _site
      - name: Commit rendered site
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add _site
          git commit -m "Render website" || echo "No changes"
          git push
