name: Render Quarto website

# Trigger on push to main or manual run
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # Setup Quarto
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      # Render website (all languages)
      - name: Render website with babelquarto
        run: Rscript -e 'babelquarto::render_website()'
        env:
          BABELQUARTO_CI_URL: https://anavalladares.netlify.app

      # Commit generated _site
      - name: Commit rendered site
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add _site
          git commit -m "Render website" || echo "No changes"
          git push
